<?php
/**
 * Created by PhpStorm.
 * User: hofer
 * Date: 09.06.2017
 * Time: 15:49
 */

/**
 * Implements hook_menu().
 */
function studienverlauf_popup_menu()
{
    $items['studienverlauf'] = array(
        'title' => 'Studienverlauf',
        'access arguments' => array('access content'),
        'page callback' => 'studienverlauf_popup_popup',
    );

    return $items;
}

function studienverlauf_popup_popup() {
    module_load_include('inc', 'popup', 'includes/popup.api');

    $attributes = array(
        'node' => 14,
    );

    return popup(array('node' => 13));

}

/**
 * Implements hook_node_view().
 */
function studienverlauf_popup_node_view($node, $view_mode, $langcode)
{
    //dsm($node);
    //dsm($node);
    drupal_add_css(drupal_get_path('module','studienverlauf_popup') . '/css/studienverlauf_popup.css');
    module_load_include('inc', 'popup', 'includes/popup.api');

    $img = "<img src='" . drupal_get_path('module', 'studienverlauf_popup') . "/Studienstruktur.jpg'>'";
    $markup = '<p>Die Regelstudienzeit im Bachelor-Studium Wirtschaftsinformatik an der Universität Hildesheim beläuft 
                    sich auf insgesamt sechs Semester. Innerhalb der ersten vier Studienhalbjahren wird der Fokus auf 
                    die Vermittlung der Grundlagen gelegt. Neben den bereits genannten Oberthemen im vorherigen Absatz werden 
                    auch mathematische Grundlagen gelehrt, die aus insgesamt drei Abschnitten bestehen. 
                    Nach dem Grundlagen-Teil gibt es die Möglichkeit, im Rahmen eines zehnwöchigen Pflichtpraktikums 
                    die gelernten Studieninhalte bei einem der insgesamt rund 40 Partnerunternehmen 
                    der Universität praktisch anzuwenden. 
                    Oft besteht im Anschluss die Möglichkeit auf eine Werkstudententätigkeit oder 
                    auch eine Kooperation mit dem Unternehmen bei der Fertigung der dreimonatigen Bachelor-Arbeit, 
                    mit der das Studium abgeschlossen wird. Neben dem Pflichtpraktikum kann zwischen vielen verschiedenen 
                    weiteren Kursen gewählt werden, um sich bereits im Bachelor-Studiengang auf 
                    ein Themengebiet zu spezialisieren.</p>
                    <p>Informationen zum Studienverlauf finden Sie hier:</p> ' .

                    popup_element('Studienstruktur',
                        '<img src="http://localhost/wi_landing_page/sites/default/files/Studienstruktur.jpg">',
                        array('effect' => 'fade', 'class' => 'Studienstruktur'));


    //$markup = studienverlauf_popup_content();
    if($node->nid == 10) {
        $node->content['body'][0] = array(
            '#markup' => $markup,

            //'#theme' => 'field',


        );
    }
    //dsm($node);
}

